### PR TITLE
R text-classifier example

### PR DESCRIPTION
**Pull request by baieric**
@iandewancker @pfhayes 

The formula used by glmnet is here: https://web.stanford.edu/~hastie/glmnet/glmnet_alpha.html#log

I feel like we should include that somewhere, but I wasn't sure where.

### CODE REVIEW

**Comment by baieric** [comment]
Rotated the client key I accidentally exposed. 😨

**Comment by iandewancker** [comment]
looks good to me.  clean easy enough to read, someone could probably extend this to do something else.  great work eric

**Comment by pfhayes** [comment]
looks great!

**Comment by alexandraj777** [comment]
Could we add some more comments? We should assume that in the average case someone jumps straight to the R code and bypasses the README, so we'll need to do a lot of the SigOpt showcasing in the comments. Here's an example: https://github.com/sigopt/sigopt-examples/blob/master/random-forest/r/random_forest.R

**Pull request merged**
