### PR TITLE
 Remove spark master slave node steps

### PR DESCRIPTION
**Pull request by nakulpathak3**
Spark submit is able to run without the master and slave nodes started. Thanks @taylorjacklespriggs for picking up on that

### CODE REVIEW

**Comment by alexandraj777** [comment]
Do we need to move these to a different spot?

**Comment by nakulpathak3** [comment]
what do you mean by 'these'?

**Comment by alexandraj777** [comment]
The commands that you removed from the install step of the experiment configuration file

**Comment by nakulpathak3** [comment]
Ah okay so from what I understand from https://spark.apache.org/docs/latest/submitting-applications.html, you can run an application "locally" using `spark-submit` or you can run it on a standalone cluster. It seems the way we are running it, it is running "locally" and not using the standalone cluster. To use the standalone cluster, I'd have to investigate more on setting local variables in Docker containers via orchestrate like we do with `pythonpath`. 

So these lines are currently not doing anything and should be removed. Standalone mode is not necessary for running these files. Here's what I found as the difference between the two - "So the only difference between Standalone and local mode is that in Standalone you are defining "containers" for the worker and spark master to run in your machine (so you can have 2 workers and your tasks can be distributed in the JVM of those two workers?) but in local mode you are just running everything in the same JVM in your local machine." [[source](https://stackoverflow.com/questions/40012093/what-is-the-difference-between-spark-standalone-yarn-and-local-mode)]

cc @taylorjacklespriggs if you want to add anything

**Comment by taylorjacklespriggs** [comment]
I don't know much about spark but this fits with my understanding of how it works.

**Pull request merged**
