### PR TITLE
sigopt 1.6.0

### PR DESCRIPTION
**Pull request by pfhayes**
@alexandraj777

---
This change is [Reviewable](https://reviewable.io/reviews/sigopt/sigopt-examples/43)

### CODE REVIEW

**Comment by alexandraj777** [comment]
What are the big changes from the last version?

**Comment by pfhayes** [comment]
Hm it was supposed to be in the commit message. Did the github squash kill it?

-Patrick




On Tue, Jun 7, 2016 at 9:02 PM -0700, "Alexandra L Johnson" <notifications@github.com> wrote:












What are the big changes from the last version?

**Comment by alexandraj777** [comment]
Not seeing it?

**Comment by pfhayes** [comment]
Oh, this is sigopt-examples. The changes are in sigopt-python.
https://github.com/sigopt/sigopt-python/commit/63bd4b5ed96cd7fd3181ce1ebb7bf63cdda6384e

**Comment by alexandraj777** [comment]
Must've gotten confused looking at too many commits at once

**Pull request merged**
